server:
  port: 8091
spring:
  cloud: 
   gateway: 
    routes:
      - id: ruta-lodecrarest
          #lb:// cuando se va a acceder a través de Eureka
        uri: lb://lodecra-rest #http://localhost:8080
        predicates:
          - Path=/s-lodecra/**
        filters:
          - RewritePath=/s-lodecra/*, /      
eureka:                  
 client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${servidoreureka}:8761/eureka
