spring:
  application:
    name: lodecra-rest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: mysql://192.168.1.17:3306/lodecrajpa?serverTimezone=America/Argentina/Buenos_Aires
    username: adriana
    password: MiPass2020

server:
  port: 8838
  servlet:
    context-path: /rest

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.1.17:8761/eureka
